FROM rust:1-slim-bookworm AS builder

RUN apt-get update && apt-get install -y \
    curl pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add wasm32-unknown-unknown

RUN cargo install trunk --locked

WORKDIR /app
COPY . .

WORKDIR /app/crates/frontend
RUN trunk build --release

FROM nginx:1.29.8-alpine-slim

COPY --from=builder /app/crates/frontend/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 2211
