services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "2211:2211"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "2026:2026"
    environment:
      RUST_LOG: "info"
      PORT: "2026"
    restart: unless-stopped
