[package]
name = "algorithm"
version = "0.1.0"
edition = "2024"

[dependencies]
shared       = { path = "../shared" }
css-selector = { path = "../css-selector" }
rayon        = { workspace = true }

[dev-dependencies]
shared       = { path = "../shared" }
css-selector = { path = "../css-selector" }
