[build]
target  = "index.html"
release = true

[watch]
ignore = ["../backend", "../../target"]

[serve]
port    = 80
open    = true
address = "127.0.0.1"

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:2211/"