[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
axum               = { workspace = true }
tokio              = { workspace = true }
reqwest            = { workspace = true }
serde              = { workspace = true }
tower-http         = { workspace = true }
html-parser        = { path = "../html-parser" }
shared             = { path = "../shared" }
algorithm          = { path = "../algorithm" }
css-selector       = { path = "../css-selector" }